"""Auto generate tables from models

Revision ID: 84374f75c9fc
Revises: 
Create Date: 2022-03-01 14:17:53.091737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84374f75c9fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('stack', sa.String(), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('companyDescription', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
